on: [pull_request]

name: UR Continuous Integration

jobs:
  UnitTest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-10-08
          override: true
          target: x86_64-apple-darwin
          components: rustfmt

      - name: Run Test
        run: cargo +nightly-2024-10-08 test
